name: CI – Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - run: composer install --no-progress --prefer-dist

      - name: PHPStan
        run: vendor/bin/phpstan analyse inc -p -l 0 -v

      - name: CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 -v inc

